  name: epitodo

  on :
    push:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - uses: pixta-dev/repository-mirroring-action@v1.1.1
          with:
            target_repo_url: git@github.com:lagie-marin/EpiTodo.git
            ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}